
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: ingh_development
  username: pgingh
  password: 

test:
  <<: *default
  database: ingh_test

production:
  <<: *default
  database: ingh_production
  username: pgingh
  password: <%= ENV['INGH_DATABASE_PASSWORD'] %>